apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd-backup

resources:
  - ../../base

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: cron-etcd-backup
    path: patch-schedule.yaml
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: etcd-backup-pvc
    path: patch-pvc.yaml