apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: equeiroz-zsl2t
  name: equeiroz-zsl2t-infra-logging
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: equeiroz-zsl2t
      machine.openshift.io/cluster-api-machineset: equeiroz-zsl2t-infra-logging
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: equeiroz-zsl2t
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: equeiroz-zsl2t-infra-logging
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          node.type/servico: infra-logging
      taints:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      - key: node.type/servico
        value: logging
        effect: NoSchedule        
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 16384
          network:
            devices:
            - networkName: VM Network
          numCPUs: 4
          numCoresPerSocket: 2
          snapshot: ""
          template: equeiroz-zsl2t-rhcos-equeiroz
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: Datacenter
            datastore: /Datacenter/datastore/datastore2
            folder: /Datacenter/vm/Plataformas/Cloud/equeiroz/
            resourcePool: /Datacenter/host/cluster/Resources
            server: vcsa.rhbr-lab.com.br