apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: machine.openshift.io
      version: v1beta1
      kind: MachineSet
      name: bpr1hub01-cmv6d-infra
      namespace: openshift-machine-api
    path: patch.yaml