apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  htpasswd: YWRtaW46eS1iYXNoNUpsa0Y0c3JDbUlQam1PRVhHRDlrLm9lTjJzbTN1d1R2OGRnRXEyUkRYbjROa1FCWGIzN0c=
type: Opaque
