apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: [""]
    resources: ["nodes","namespaces"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods","pods/log"]
    verbs: ["get","list","create","delete","watch"]
