apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: cluster-monitoring-config
      namespace: openshift-monitoring
    path: patch-cm-monitoring.yaml