apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-self-provisioner
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster.btb/type
              operator: In
              values:
                - openshift
                - openshift-baremetal
                - openshift-hub
                - openshift-virt     
            - key: cluster.btb/env
              operator: In
              values:
                - prd
                - dev
                - hml  
            - key: gitops.btb/self-provisioner
              operator: In
              values:
                - enable
  template:
    metadata:
      name: '{{name}}-self-provisioner'
    spec:
      project: default
      source:
        repoURL: 'https://bancotoyota@dev.azure.com/bancotoyota/Infraestrutura/_git/Openshift-gitops-infra'
        targetRevision: HEAD
        path: 'components/projects/base'
      destination:
        server: '{{server}}'
        namespace: openshift-config
      syncPolicy:
        automated:
          prune: true
          selfHeal: true



