apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-oadp
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: env
                    operator: In
                    values: [des, hml, prd]
                  - key: backup
                    operator: In
                    values: [oadp-1.0, oadp-1.1, oadp-1.2]
          - list:
              elements:
                - component: operator
                  pathTpl: 'components/oadp/operator/overlays/{{metadata.labels.backup}}'
                  suffix: 'oadp-operator'
                - component: instance
                  pathTpl: 'components/oadp/instance/overlays/{{metadata.labels.env}}'
                  suffix: 'oadp-instance'
  template:
    metadata:
      name: '{{name}}-{{.suffix}}'
    spec:
      project: appsets
      destination:
        server: '{{server}}'
        namespace: openshift-adp
      source:
        repoURL: 'https://github.com/ederqueirozdf/infra-gitops-openshift.git'
        targetRevision: HEAD
        path: '{{ .pathTpl }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true