apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oauth-htpass-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: appset.enable/oauth
              operator: In
              values: ["htpass", "ldap"]
            - key: env
              operator: In
              values: ["prd", "des", "hml"]    
  template:
    metadata:
      name: '{{name}}-oauth-htpass'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ederqueirozdf/infra-gitops-openshift.git'
        targetRevision: HEAD
        path: '../components/oauth/overlays/{{metadata.labels.oauth}}'
      destination:
        server: '{{server}}'
        namespace: openshift-config
      syncPolicy:
        automated:
          prune: true
          selfHeal: true